//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipe()
        {
            this.Equipe_Campeonato = new HashSet<Equipe_Campeonato>();
            this.Jogador = new HashSet<Jogador>();
            this.Jogo = new HashSet<Jogo>();
            this.Jogo1 = new HashSet<Jogo>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string nome_completo { get; set; }
        public System.DateTime data_fundacao { get; set; }
        public byte[] escudo { get; set; }
        public Nullable<int> id_estadio { get; set; }
        public Nullable<int> id_treinador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipe_Campeonato> Equipe_Campeonato { get; set; }
        public virtual Estadio Estadio { get; set; }
        public virtual Treinador Treinador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jogador> Jogador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jogo> Jogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jogo> Jogo1 { get; set; }
    }
}
