//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escalacao
    {
        public int id_jogador { get; set; }
        public int id_jogo { get; set; }
        public int nr_cartao_amarelo { get; set; }
        public int nr_cartao_vermelho { get; set; }
        public bool fl_titular { get; set; }
    
        public virtual Jogador Jogador { get; set; }
        public virtual Jogo Jogo { get; set; }
    }
}
