//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public string cpf { get; set; }
        public string apelido { get; set; }
        public string nome { get; set; }
        public Nullable<int> num_camisa { get; set; }
        public string posicao { get; set; }
        public string nacionalidade { get; set; }
        public System.DateTime data_nasc { get; set; }
        public string email { get; set; }
        public byte[] foto { get; set; }
    }
}
