//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jogador()
        {
            this.Escalacao = new HashSet<Escalacao>();
        }
    
        public string cpf { get; set; }
        public string apelido { get; set; }
        public string nome { get; set; }
        public Nullable<int> num_camisa { get; set; }
        public string posicao { get; set; }
        public string nacionalidade { get; set; }
        public System.DateTime data_nasc { get; set; }
        public string email { get; set; }
        public byte[] foto { get; set; }
        public int id { get; set; }
        public Nullable<int> id_equipe { get; set; }
    
        public virtual Equipe Equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Escalacao> Escalacao { get; set; }
    }
}
