//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jogo()
        {
            this.Escalacao = new HashSet<Escalacao>();
        }
    
        public int id { get; set; }
        public int id_equipe_casa { get; set; }
        public int id_equipe_visitante { get; set; }
        public int id_arbitro { get; set; }
        public int id_campeonato { get; set; }
        public Nullable<int> num_gol_casa { get; set; }
        public Nullable<int> num_gol_visitante { get; set; }
    
        public virtual Arbitro Arbitro { get; set; }
        public virtual Campeonato Campeonato { get; set; }
        public virtual Equipe Equipe { get; set; }
        public virtual Equipe Equipe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Escalacao> Escalacao { get; set; }
    }
}
