//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogo
    {
        public int id { get; set; }
        public int id_equipe_casa { get; set; }
        public int id_equipe_visitante { get; set; }
        public int id_arbitro { get; set; }
        public int id_campeonato { get; set; }
        public int num_gold_casa { get; set; }
        public int num_gol_visitante { get; set; }
    
        public virtual Arbitro Arbitro { get; set; }
        public virtual Campeonato Campeonato { get; set; }
        public virtual Equipe Equipe { get; set; }
        public virtual Equipe Equipe1 { get; set; }
    }
}
